### ISSUE TITLE
SAFE_PATH_PREFIX is not safe at all

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#1002]
1. Run `inspect(Object.assign(Promise.resolve({}), {"##-value": []}))`
2. Expand `<value>`

Result: both `<value>` and `"##-value"` are expanded.

This happens for all pseudo-nodes except `<prototype>`, which has its own problem (#1001).

Either prefix normal properties with something different than `##-`, or use symbols instead of strings for paths. The latter probably requires more work but seems the proper approach IMO.

**Comment by jasonLaster** [comment]
Yes, we discussed symbols early on and decided that the `##-` prefix was worth the risk for the time being. We should address this hack at some point.

**Comment by nchevobbe** [comment]
I agree of the issue, even if it's unlikely to happen.
We can't use just symbol for path, since each path is built upon the previous one.
But we could make the path an array which would be something like
```js
[
  "/root"
  "a",
  Symbol(NODE_TYPE.PROTOTYPE)
]
```
and use Sets and Maps in the state when we want to refer to them.
I think it shouldn't be too hard to do

**Comment by nchevobbe** [comment]
`SAFE_PATH_PREFIX` does not exist anymore (removed in https://github.com/devtools-html/devtools-core/pull/1013)
