### ISSUE TITLE
Merge string and longString reps

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#550]
Currently we have 2 reps to deal with strings.
It's unfortunate because when we add feature we have to look at 2 places (or we could forget one).
It should be doable to only have the String one and adapt it for longString.

**Comment by kootoopas** [comment]
@nchevobbe Hello!

Since there are a couple of issues (#835, #836, #518) that seem dependent on this, which I'm also interested in resolving, I'll tackle this one first.

Shame that there's no ability to `/claim` in this repo though! It really motivates me to publicly state that I'm going to undertake something and I'm pretty sure I'm not the only one who feels this way. :)

**Comment by nchevobbe** [comment]
@jasonLaster , we need `/claim` support here :D
