### ISSUE TITLE
Add support for multiline values

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#807]
From https://bugzilla.mozilla.org/show_bug.cgi?id=994756

> It would be great if we would be able to display multiline strings in the variable view. This would allow us to e.g. display the first three lines of a script.

Right now, if you evaluate : 
```js
console.dir({
  multiline: `
I am 
   on 
  multiple
         lines.
`
})
```

You get 
```
▼ {…}
 | multiline: "\nI am \n   on \n  multiple\n         lines.\n"
 | __proto__ : 
```
i.e. escaped line breaks.

A patch for this issue would display : 
```
▼ {…}
 | multiline: `
 |  I am 
 |     on 
 |    multiple
 |           lines.
 |  `
 |  __proto__ : 
```

Not sure though

**Comment by kootoopas** [comment]
I find the proposed multiline representation more visually scannable, since it replicates its originally typed/constructed form.

It seems that chrome handles it like that too.
<img width="130" alt="screen shot 2017-12-15 at 10 50 37 am" src="https://user-images.githubusercontent.com/601001/34034352-c466f344-e186-11e7-991c-e4e2e3c23770.png">


I haven't figured out how to get the string wrappers yet (\`, ', "), but I'm not sure if we'd care about that anyway. `¯\_(ツ)_/¯`

**Comment by Loirooriol** [comment]
I think

```js
inspect({json: JSON.stringify({foo: {bar: 123}}, null, 2)})
```

should be displayed with a `▶` arrow

```
▼ {…}
| ▶ json: "{\n  \"foo\": {\n    \"bar\": 123\n  }\n}"
| ▶ <prototype>: Object { … }
```

and expanding it would produce

```
▼ {…}
| ▼ json: `{
|     "foo": {
|       "bar": 123
|     }
|   }`
| ▶ <prototype>: Object { … }
```

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6124
