### ISSUE TITLE
ElementNode attribute are not cropped

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#835]
**Steps to reproduce:**
1. Evaluate:
```js
var div = document.createElement("div");
div.setAttribute("data-test","a".repeat(5000));
div;
```

**Expected results:**
The `data-test attribute` is cropped 

**Actual results:**
It is not cropped (and does not wrap)

**Comment by kootoopas** [comment]
Call me weird but I find the expected cropped display hindering accessibility, since there's no way of seeing cropped attributes. Shouldn't they wrap ideally?

Chrome offers the same single line non-crop functionality btw:
<img width="560" alt="screen shot 2017-12-15 at 10 41 40 am" src="https://user-images.githubusercontent.com/601001/34033902-e90986d2-e184-11e7-9eb3-736c7b82514a.png">

**Comment by nchevobbe** [comment]
I'd say we could crop and have a title attribute to show the whole string. Or we could make the ellipsis clickable for people who want to see the whole rule.

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6121
