### ISSUE TITLE
Network requests that are subject to Tailing should be identified as such in the Developer Tools

### ISSUE THREAD

**Issue by frio80** [devtools-html/devtools-core#871]
It would be great if the Dev Tools Network Monitor tab would show which requests were subject to tailing[0].  It would also be great to show _why_, how long and any other information available about the tailing action.

[0] https://www.janbambas.cz/firefox-57-delays-requests-tracking-domains

**Comment by nchevobbe** [comment]
Hello @frio80 , thanks for filing this issue.
The netmonitor development does not happen in Github though, but on the Firefox repository. 
I created a bug on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1426925, so we can work on it. I'll close this bug since it is now tracked in the proper place.

If you want to follow the process on that bug, you can create a Bugzilla account with your Github account.
